title: Shivam Panigrahi
#logo: /assets/img/headshot_circle.png
logo: /assets/img/dsc_0008-modified.png
description: Experienced IT innovator known for consistently delivering pioneering solutions and spearheading impactful digital transformations.
show_downloads: true
theme: jekyll-theme-minimal
